### PR TITLE
Add comments to metadb po_lines_phys_mat_type, po_acq_unit_ids, and invoice_voucher_lines_fund_distributions

### PR DESCRIPTION
**Pull request by scanedastanford**
```
All queries:
- [ ] Release notes added or updated in CHANGES.md
- [ ] Query runs without errors
- [ ] Query output is correct
- [ ] Query logic is clear and well documented
- [ ] Query is readable and properly indented with spaces (not tabs)
- [ ] Table and column names are in all-lowercase
- [ ] Quotation marks are used only where necessary

Report queries:
- [ ] Query has complete user documentation
    - [ ] Purpose of report
    - [ ] Sample output
    - [ ] Query instructions

Derived tables:
- [ ] Query begins with user documentation in comment lines
- [ ] File name is listed in `runlist.txt` after dependencies
- [ ] All columns have indexes
- [ ] Table is vacuumed and analyzed
```

### CODE REVIEW

**Review by AlaoSUL — CHANGES_REQUESTED** [review]
A small change for the po_lines_phys_mat_type  

Please move the user documentation (below) to the top of the query so it's consistent with the others. Otherwise, good to go after that small change. Thanks!

-- Create a derived table that extract physical resource material types from purchase order lines

All queries:
- [x] Release notes added or updated in CHANGES.md
- [x] Query runs without errors
- [x] Query output is correct
- [x] Query logic is clear and well documented
- [x] Query is readable and properly indented with spaces (not tabs)
- [x] Table and column names are in all-lowercase
- [x] Quotation marks are used only where necessary

Report queries:
- [] Query has complete user documentation
    - [] Purpose of report
    - [] Sample output
    - [] Query instructions

Derived tables:
- [] Query begins with user documentation in comment lines
- [x] File name is listed in `runlist.txt` after dependencies
- [x] All columns have indexes
- [x] Table is vacuumed and analyzed

**Comment by scanedastanford** [comment]
@AlaoSUL Thanks Alex! I've edited the user documentation comment for po_lines_phys_mat_type

**Review by AlaoSUL — APPROVED** [review]
Thanks Suzette! Good to go now! 

All queries:
- [x] Release notes added or updated in CHANGES.md
- [x] Query runs without errors
- [x] Query output is correct
- [x] Query logic is clear and well documented
- [x] Query is readable and properly indented with spaces (not tabs)
- [x] Table and column names are in all-lowercase
- [x] Quotation marks are used only where necessary

Report queries:
- [ ] Query has complete user documentation
    - [ ] Purpose of report
    - [ ] Sample output
    - [ ] Query instructions

Derived tables:
- [x] Query begins with user documentation in comment lines
- [x] File name is listed in `runlist.txt` after dependencies
- [x] All columns have indexes
- [x] Table is vacuumed and analyzed

**Review by adoerrer — APPROVED** [review]
All queries und results look good, thank you!

All queries:
* [x]  Release notes added or updated in CHANGES.md
* [x]  Query runs without errors
* [x]  Query output is correct
* [x]  Query logic is clear and well documented
* [x]  Query is readable and properly indented with spaces (not tabs)
* [x]  Table and column names are in all-lowercase
* [x]  Quotation marks are used only where necessary
 
 Derived tables:
* [x]  Query begins with user documentation in comment lines
* [x]  File name is listed in `runlist.txt` after dependencies 
* [x]  All columns have indexes
* [x]  Table is vacuumed and analyzed

**Pull request merged**
