### PR TITLE
RA/UM - Loans and renewals count report by year

### LINKED ISSUE #721: RA/UM - Loans and renewals count report by year
The report should shown informations to:

- The counts for loans and renewals for each items by year (current year and the 2 years before) 
- The sums of all loans and renewals that have ever existed for each item
- A summary of all loans and renewals that have ever existed for an item in a combined count

### PR DESCRIPTION
**Pull request by stdombek**
Closes #721 

The report should shown informations to:

-  The counts for loans and renewals for each items by year (current year and the 2 years before)
-  The sums of all loans and renewals that have ever existed for each item
-  A summary of all loans and renewals that have ever existed for an item in a combined count

```
All queries:
- [ ] Pull request is based on a new branch (not main)
- [ ] Pull request scope is not overly broad
- [ ] Release notes have been added or updated in CHANGES.md
- [ ] Query runs without errors
- [ ] Query output is correct
- [ ] Query logic is clear and well documented
- [ ] Query is readable and properly indented with spaces (not tabs)
- [ ] Table and column names are in all-lowercase
- [ ] Quotation marks are used only where necessary

Report queries:
- [ ] Query has complete user documentation
    - [ ] Purpose of report
    - [ ] Sample output
    - [ ] Query instructions

Derived tables:
- [ ] Query begins with user documentation in comment lines
- [ ] File name is listed in `runlist.txt` after dependencies
- [ ] All columns have indexes
- [ ] Table is vacuumed and analyzed
```

### CODE REVIEW

**Review by VandanaShah-Cornell — APPROVED** [review]
Everything looks good, there isn't a lot of data to check the output, but the two rows that are produced look just fine. 

All queries:
- [x] Pull request is based on a new branch (not main)
- [x] Pull request scope is not overly broad
- [x] Release notes have been added or updated in CHANGES.md
- [x] Query runs without errors
- [x] Query output is correct
- [x] Query logic is clear and well documented
- [x] Query is readable and properly indented with spaces (not tabs)
- [x] Table and column names are in all-lowercase
- [x] Quotation marks are used only where necessary

Report queries:
- [x] Query has complete user documentation
- [x] Purpose of report
- [x] Sample output
- [x] Query instructions

**Review by amzoss — DISMISSED** [review]
Looks good to me!

All queries:
- [x] Pull request is based on a new branch (not main)
- [x] Pull request scope is not overly broad
- [x] Release notes have been added or updated in CHANGES.md
- [x] Query runs without errors
- [x] Query output is correct
- [x] Query logic is clear and well documented
- [x] Query is readable and properly indented with spaces (not tabs)
- [x] Table and column names are in all-lowercase
- [x] Quotation marks are used only where necessary

Report queries:
- [x] Query has complete user documentation
    - [x] Purpose of report
    - [x] Sample output
    - [x] Query instructions

**Comment by nassibnassar** [comment]
This PR is still in Draft.

**Comment by stdombek** [comment]
@nassibnassar I changed the status from draft, please merge. The review has already taken place. Thanks!

**Pull request merged**
