### PR TITLE
refactored version of ACRL circulation report

### LINKED ISSUE #190: Refactor RA/UM ACRL circulation report query to use derived tables
[ACRL circulation query](https://github.com/folio-org/folio-analytics/tree/master/sql/report_queries/acrl/circulation)
[ACRL report JIRA issue in UXPROD](https://issues.folio.org/browse/UXPROD-2529)

### PR DESCRIPTION
**Pull request by amzoss**
will close #190

### CODE REVIEW

**Comment by nassibnassar** [comment]
Was this PR created by mistake?

**Comment by amzoss** [comment]
No, but I can close it if I did something wrong!

**Comment by amzoss** [comment]
I see, forgot to push last commit!

**Comment by nassibnassar** [comment]
I think it is asking you to sign the CLA; could you sign it again?  I have seen this before - it may be a bug in the CLA integration.

**Pull request merged**
