### PR TITLE
ERM - Deleted metadb derived table finance_po_inv_transactions.sql

### LINKED ISSUE #677: ERM - Delete metadb derived table finance_po_inv_transactions.sql
After the first fy rollovers in the institutions we found that this derived table is not working properly and never will. The erm wg must delete a derived table from the repository.

### PR DESCRIPTION
**Pull request by stdombek**
Closes #677 
After the first fy rollovers in the institutions we found that this derived table is not working properly and never will. The erm wg must delete this derived table from the repository.

@nassibnassar 
As agreed, here are the releases from folio-analytics where the derived table is also available.

* release-1.4 
  * https://github.com/folio-org/folio-analytics/blob/release-1.4/sql_metadb/derived_tables/finance_po_inv_transactions.sql
  * https://github.com/folio-org/folio-analytics/blob/release-1.4/sql_metadb/derived_tables/runlist.txt

### CODE REVIEW

**Review by adoerrer — APPROVED** [review]
Thank you for the changes. We have discussed this several times and it make sense to remove this derived table.

**Review by amzoss — APPROVED** [review]
This looks good to me.

**Comment by nassibnassar** [comment]
The statement `DROP TABLE IF EXISTS finance_po_inv_transactions` should be preserved to clean up leftover tables.  I will make this change.

**Comment by nassibnassar** [comment]
Applied as commit 475e6b19655c4c78b70f289fd5762ad915c840a7

**Comment by nassibnassar** [comment]
Applied to branch `release-1.4` as commit 8f67b6114181166a6b08dace5a498d69fc9e5f1c

**Pull request closed without merging**
