### PR TITLE
new metadb table Holdings statements supplements

### PR DESCRIPTION
**Pull request by natalyapik**
create new metadb table holdings_statement_supplement

### CODE REVIEW

**Comment by jenmawe** [comment]
- [] Query runs
- [x] Data output makes sense
- [x] Data types look correct
- [x] Query logic seems correct
- [x] Column names make sense and are spelled correctly
- [] Query syntax and style are appropriate (e.g., correct use of double quotes, lower case for data types)

For derived tables:
- [x] query has indexes on columns
- [x] vacuum analyze has been added to the bottom
- [x] table appears in runlist.txt at an appropriate point

I just noticed that on line 11, 23, and 39 statement has double quotes. I was able to run the query when I removed the quotes. I realize that sometimes DBeaver will have the warning for some words. If you want, you could have holdings_statement instead of just using the word statement which will then avoid any warnings.

**Review by jenmawe — CHANGES_REQUESTED** [review]
statement is in quotes. See comment in conversation.

**Review by jenmawe — APPROVED** [review]
Looks great. All checks passed now

- [x] Query runs
- [x] Data output makes sense
- [x] Data types look correct
- [x] Query logic seems correct
- [x] Column names make sense and are spelled correctly
- [x] Query syntax and style are appropriate (e.g., correct use of double quotes, lower case for data types)

For derived tables:
- [x] query has indexes on columns
- [x] vacuum analyze has been added to the bottom
- [x] table appears in runlist.txt at an appropriate point

**Review by adoerrer — APPROVED** [review]
Runs and looks great, thank you! 

- [x] Query runs
- [x] Data output makes sense
- [x] Data types look correct
- [x] Query logic seems correct
- [x] Column names make sense and are spelled correctly
- [x] Query syntax and style are appropriate (e.g., correct use of double quotes, lower case for data types)

For derived tables:
- [x] query has indexes on columns
- [x] vacuum analyze has been added to the bottom
- [x] table appears in runlist.txt at an appropriate point

**Review by jenmawe — APPROVED** [review]

**Pull request merged**
