### PR TITLE
Update holdings_ext.sql

### PR DESCRIPTION
**Pull request by VandanaShah-Cornell**
/*Changes: 
1. Fixed to bring in the correct data for the 'updated_by_user_id' field; it was bringing in data from the created by userid rather than the updated_by_user_id. 
2. The holdings_supress field needed to be cast as Boolean. 
3. The json extract for ill_policy_id needed to be cast as UUID.
4. Cast the date fields as "timestamptz" (changed from text)
5. Cast the discovery_suppress field as Boolean (changed from text)
6. Cast the extract of updatedByUserId as UUID (changed from text) */

### CODE REVIEW

**Comment by VandanaShah-Cornell** [comment]
This PR closes issue #856

**Review by trapido — CHANGES_REQUESTED** [review]
There are a couple of problems: 
1.The query won’t run because the CTE is not properly terminated with “)” and the main query is missing a select statement. The easiest way to fix this might be to remove line 11, “WITH holdings AS ( “.
2.I think that joining holdings_record__t and holdings_record tables might be redundant: it should be possible to extract all of the data out of holdings_record table.

All queries:
- [x] PR Title and Description are accurate and thorough
- [x] PR is based on a new branch (not main)
- [x] PR scope is not overly broad
- [ ] Query runs without errors
- [ ] Query output is correct
- [ ] Query logic is clear and well documented
- [x] Query is readable and properly indented
- [x] Table and column names are in all-lowercase
- [x] Quotation marks are used only where necessary
- [x] JSON extraction is in standard form, for example:
      LDP:     t #>> '{f1,f2,f3}'    [for compatibility across LDP 1 & 2]
      Metadb:  jsonb_extract_path_text(t, f1, f2, f3)

Derived tables:
- [x] First line is "--metadb:table" directive, followed by blank line
- [x] User documentation in comment lines, followed by blank line
- [x] File name is listed in `runlist.txt` after dependencies

**Comment by VandanaShah-Cornell** [comment]
My apologies for these errors, looks like I was testing the query without creating a table, and then sent the version I was mucking around with as a PR, instead of the cleaned version.

**Comment by VandanaShah-Cornell** [comment]
Hi Irina,

I am so sorry about this, looks like I was testing the query without creating a table, and then sent version I was mucking around with as a PR, instead of the cleaned version.

-Vandana

**Comment by VandanaShah-Cornell** [comment]
Re: Using both holdings_record__t and holdings_record tables : most of the fields are already extracted from the jsonb and are in the holdings_record__t table, except for three fields that needed to be extracted from the holdings_record table. It is easier to use the transformed table, is there any reason to not do this? Seems like extra work to extract fields that are already in transformed tables.

**Comment by trapido** [comment]
Thank you very much, Vandana! Everything looks good. Just one minor thing: should the metadb dirctive read "--metadb:table holdings_ext" instead of "--Metadb: holdings_ext"? 
Regarding using holdings_record__t and holdings_record tables in the same query, there is nothing wrong with this, I just remember Nassib mentioning that this is not efficient because we are essentially joining two copies of the same data.

**Pull request merged**
