### PR TITLE
Update of ACRL documentation and ACRL Collection Expenditures A & B

### PR DESCRIPTION
**Pull request by NancyBolduc**
Adding ACRL- Library Collections folder, documentation and update ACRL Collection Expenditures queries. Replacing the invoice_transactions table by folio_reporting.finance_transaction_invoices and adding the Expense class table.

### CODE REVIEW

**Review by adoerrer — CHANGES_REQUESTED** [review]
Looks and works good overall but for queries `ACRL Collection Expenditures A.sql `and` ACRL Collection Expenditures B.sql` the substitution of `approval_date` by `payment_date` should be also mentioned in the top documentation and the filters. 
I also might suggest to replace underscore on each whitespace in the file names.

**Review by nassibnassar — COMMENTED** [review]
Could I also request all-lowercase file names, in addition to using underscores instead of spaces?

**Comment by nassibnassar** [comment]
@NancyBolduc If you are not sure how to rename the files, I can do that.

**Comment by nassibnassar** [comment]
Also I see sbeltaine listed as a second reviewer.  Does she know that she is being asked to review?

**Review by sbeltaine — APPROVED** [review]
Reviewed and approved

**Comment by NancyBolduc** [comment]
> 
> 
> Looks and works good overall but for queries `ACRL Collection Expenditures A.sql `and` ACRL Collection Expenditures B.sql` the substitution of `approval_date` by `payment_date` should be also mentioned in the top documentation and the filters.
> I also might suggest to replace underscore on each whitespace in the file names.

Thanks for reviewing Axel! Sorry for the delay in replying, I was on vacation. I made those changes, please review.

**Comment by NancyBolduc** [comment]
> 
> 
> @NancyBolduc If you are not sure how to rename the files, I can do that.

Hi Nassib!  Sorry for the delay in replying, I was on vacation. If you don't mind renaming the files, that would be great! Thanks!

**Review by adoerrer — APPROVED** [review]
Thanks, looks good!

**Comment by nassibnassar** [comment]
Thanks!  It seems like we are missing a `README.md` file in both `acrl/` and `title_count_brief/`.  Usually we have thought of `README.md` as the starting point for documentation of a report/query.

**Comment by NancyBolduc** [comment]
Nassib - We found out that the long version of ‘Title count’ and ‘Item count’ were much more adequate for ARCL. Since we did not want to get rid of them, since someone as some point created them and they can still be useful, we renamed them ‘brief’ and moved them to the queries list. If you think we should add a README note, we can do that.

Nancy Bolduc
Cornell University Library
Library Finance and Budget Office
232 Olin Library
Cornell University
Ithaca, NY 14853
Tel: 607-255-5102/607-220-4349
Fax: 607-254-3554
Pronouns: she/her/hers

Due to staffing changes necessitated by the current public health concerns my response might be slower than usual. If your message is urgent, please send it with the Subject header “URGENT”. Thank you!

**Comment by nassibnassar** [comment]
I think we should merge this PR, but it would be good to have a README.md in every directory unless the content has been explained in a parent directory's README.md.  A README.md can also link to other documentation files if needed.

**Pull request merged**
