### PR TITLE
Added derived tables fixes #376 and #364

### LINKED ISSUE #376: Create derived table for transactions with order context

### PR DESCRIPTION
**Pull request by adoerrer**

### CODE REVIEW

**Comment by nassibnassar** [comment]
Should this PR update runlist.txt?

**Comment by adoerrer** [comment]
> Should this PR update runlist.txt?

Yes, thank you for the reminder. I now added them to runlist.txt and modified invoice_transactions.sql to run even if there are no invoices.

**Comment by lib-eric** [comment]
Testing with our system, running into issues with 'purchase_order_transactions' when trying to run line 31 (pol.description AS pol_description,).

This might just be due to our new refresh. We have had issues where the if a field has not been populated in any record, it does NOT get added to the tables. Or we just do not have complete data yet.

No indexes over MS Access's limit of 32 - so good!

Limited knowledge of finance and funds side but from looking at the query it looks good as far as I can tell.

**Comment by nassibnassar** [comment]
On the issue with `purchase_order_transactions`, it sounds like that might possibly result from the `purchaseOrderTransactions` JSON field not being included in the data extracted from a FOLIO instance.  If so, that is a known issue with LDP that we will try to address at some point in Metadb.  For now we have a standard workaround which is to replace the column references in the query with `json_extract_path_text() AS ...`, which returns `NULL` if the field is missing.

**Comment by adoerrer** [comment]
Thanks, have bow added the workaround for pol_description as well.

**Pull request merged**
