### PR TITLE
RA/UM - Fixes for derived table 'instance_ext' for Metadb

### LINKED ISSUE #772: RA/UM - Fixes for derived table 'instance_ext' for Metadb
The derived table 'instance_ext' for Metadb does not correspond 1:1 to the version for LDP1. For this reason, reports for metadb using this table cannot work.

### PR DESCRIPTION
**Pull request by stdombek**
Closes #772 

The derived table "instance_ext" for metadb did not correspond 1:1 to the version for LDP1. Ported reports for MetaDB using this table did not work. The attributes now match those of the LDP1 version. Two attributes that were only in the Metadb version have been left so as not to interfere with any existing reports.

### CODE REVIEW

**Review by VandanaShah-Cornell — APPROVED** [review]
All queries:
- [x] PR Title and Description are accurate and thorough
- [x] PR is based on a new branch (not main)
- [x] PR scope is not overly broad
- [x] Query runs without errors
- [x] Query output is correct
- [x] Query logic is clear and well documented
- [x] Query is readable and properly indented
- [x] Table and column names are in all-lowercase
- [x] Quotation marks are used only where necessary
- [x] JSON extraction is in standard form, for example:
      LDP:     t #>> '{f1,f2,f3}'    [for compatibility across LDP 1 & 2]
      Metadb:  jsonb_extract_path_text(t, f1, f2, f3)

Derived tables:
- [x] First line is "--metadb:table" directive, followed by blank line
- [x] User documentation in comment lines, followed by blank line
- [x] File name is listed in `runlist.txt` after dependencies

**Comment by stdombek** [comment]
PR blocks #746

**Review by eliana-flo — CHANGES_REQUESTED** [review]
All queries:
- [x] PR Title and Description are accurate and thorough
- [x] PR is based on a new branch (not main)
- [x] PR scope is not overly broad
- [x] Query runs without errors
- [x] Query output is correct
- [ ] Query logic is clear and well documented
- [x] Query is readable and properly indented
- [x] Table and column names are in all-lowercase
- [x] Quotation marks are used only where necessary
- [x] JSON extraction is in standard form, for example:
      LDP:     t #>> '{f1,f2,f3}'    [for compatibility across LDP 1 & 2]
      Metadb:  jsonb_extract_path_text(t, f1, f2, f3)

Derived tables:
- [x] First line is "--metadb:table" directive, followed by blank line
- [x] User documentation in comment lines, followed by blank line
- [x] File name is listed in `runlist.txt` after dependencies

instance__t.source appears twice in the SELECT statement (once with the alias "instance_source" and once with the alias "record_source.") 

Slight typo for the comment on cataloged_date, it should be "when it was considered cataloged" not "when is was"

Grammar error in the comment on instance_source & record_source, instead of "the metadata source and ITS format of the underlying reocrd" it should be "the metadata source and THE format of the underlying record"

**Comment by stdombek** [comment]
@eliana-flo Thanks for the review. It is a 1:1 port of the derived table for LDP. I corrected the comments, but this would probably have to happen for the LDP version as well. 
I also noticed the duplicate usage of instance__t.source. But to maintain compatibility I kept the duplication. This could otherwise disrupt the porting/migration of the reports from other libraries.

**Review by eliana-flo — APPROVED** [review]

**Comment by VandanaShah-Cornell** [comment]
For these two lines:
 instance__t.instance_type_id AS type_id,
 instance_type__t.name AS type_name,

I suggest naming them instance_type_id and instance_type_name. I have noticed people getting confused over this, even when it may seem quite obvious.

**Review by VandanaShah-Cornell — APPROVED** [review]
All queries:
- [x] PR Title and Description are accurate and thorough
- [x] PR is based on a new branch (not main)
- [x] PR scope is not overly broad
- [x ] Query runs without errors
- [x] Query output is correct
- [x] Query logic is clear and well documented
- [x] Query is readable and properly indented
- [x] Table and column names are in all-lowercase
- [x] Quotation marks are used only where necessary
- [x] JSON extraction is in standard form, for example:
      LDP:     t #>> '{f1,f2,f3}'    [for compatibility across LDP 1 & 2]
      Metadb:  jsonb_extract_path_text(t, f1, f2, f3)

Derived tables:
- [x] First line is "--metadb:table" directive, followed by blank line
- [x] User documentation in comment lines, followed by blank line
- [x] File name is listed in `runlist.txt` after dependencies

**Comment by stdombek** [comment]
> For these two lines: instance__t.instance_type_id AS type_id, instance_type__t.name AS type_name,
> 
> I suggest naming them instance_type_id and instance_type_name. I have noticed people getting confused over this, even when it may seem quite obvious.

I think that is a good point and I agree with you. But this is a 1:1 port of the LDP derived table and we use this one in some reports. If change the attribute names here, we have to change all dependencies.

**Pull request merged**
