### PR TITLE
BUG FIX for Feesfines accounts actions

### PR DESCRIPTION
**Pull request by natalyapik**
fixes missing "name' in the json extract for json_extract_path_text(fa.data, 'status') AS fine_status, line 19 
to json_extract_path_text(fa.data, 'status', 'name') AS fine_status

### CODE REVIEW

**Review by amzoss — CHANGES_REQUESTED** [review]
The query itself is fine, but it would be a bit better if this PR didn't include a separate, unrelated file (po_instance.sql). Since that file is being reviewed separately, could it be removed from this PR?

All queries:
- [x] Pull request has a complete description
- [x] Query runs without errors
- [x] Query output is correct
- [x] Query logic is clear and well documented
- [x] Query is readable and properly indented
- [x] Table and column names are in all-lowercase
- [x] Quotation marks are used only where necessary

Derived tables:
- [x] Query begins with user documentation in comment lines
- [x] File name is listed in `runlist.txt` after dependencies
- [x] All columns have indexes
- [x] Table is vacuumed and analyzed

**Review by adoerrer — CHANGES_REQUESTED** [review]
Hi @natalyapik thank you! The query on feesfines_accounts_actions runs and looks fine. As Angela I'd suggest to remove po_instance.sql from this PR. Thanks!

All queries:
 
     * [x]  Pull request has a complete description
 
     * [x]  Query runs without errors
 
     * [x]  Query output is correct
 
     * [x]  Query logic is clear and well documented
 
     * [x]  Query is readable and properly indented
 
     * [x]  Table and column names are in all-lowercase
 
     * [x]  Quotation marks are used only where necessary
 
 
 Derived tables:
 
     * [x]  Query begins with user documentation in comment lines
 
     * [x]  File name is listed in `runlist.txt` after dependencies
 
     * [x]  All columns have indexes
 
     * [x]  Table is vacuumed and analyzed

**Review by adoerrer — APPROVED** [review]
Looks good now, thanks @natalyapik !

**Comment by nassibnassar** [comment]
Applying the fix manually and closing this PR, to avoid deleting sql/derived_tables/po_instance.sql

**Pull request closed without merging**
