### PR TITLE
ERM - Report 'eusage_counter_rpt_pr' for Metadb

### LINKED ISSUE #765: ERM - Create Report 'eusage_counter_rpt_pr' for Metadb
This report is intended to contain data from the FOLIO app eUsage. In this case, the report contains only data for Platform Master Reports (PR). The required attributes can be found at https://medialibrary.projectcounter.org/file/The-Friendly-Guide-for-Librarians . In addition to this attributes we need some metadata to the downloaded report.

Attributes:

- id
- report_name
- report_id
- release
- institution_name
- institution_id
- reporting_period_start
- reporting_period_end
- created
- created_by
- report_year_mounth
- platform
- data_type
- access_type
- access_method
- metric_type
- reporting_period_total

#648 and #649.

### PR DESCRIPTION
**Pull request by stdombek**
Closes #765 
This report is intended to contain data from the FOLIO app eUsage. In this case, the report contains only data for Platform Master Reports (PR). The required attributes can be found at https://medialibrary.projectcounter.org/file/The-Friendly-Guide-for-Librarians . In addition to this attributes there are attributes to the downloaded COUNTER report.

For performance reasons, the arrays are read based on positions.

### CODE REVIEW

**Review by VandanaShah-Cornell — APPROVED** [review]
All queries:
- [x] PR Title and Description are accurate and thorough
- [x] PR is based on a new branch (not main)
- [x] PR scope is not overly broad
- [x] Query runs without errors
- [x] Query output is correct
- [x] Query logic is clear and well documented
- [x] Query is readable and properly indented
- [x] Table and column names are in all-lowercase
- [x] Quotation marks are used only where necessary
- [x] JSON extraction is in standard form, for example:
      LDP:     t #>> '{f1,f2,f3}'    [for compatibility across LDP 1 & 2]
      Metadb:  jsonb_extract_path_text(t, f1, f2, f3)

Report queries:
- [x] Query has complete user documentation
- [x] Purpose of report
- [x] Sample output
- [x] Query instructions

**Review by VandanaShah-Cornell — APPROVED** [review]
All queries:
- [x] PR Title and Description are accurate and thorough
- [x] PR is based on a new branch (not main)
- [x] PR scope is not overly broad
- [x] Query runs without errors
- [x] Query output is correct
- [x] Query logic is clear and well documented
- [x] Query is readable and properly indented
- [x] Table and column names are in all-lowercase
- [x] Quotation marks are used only where necessary
- [x] JSON extraction is in standard form, for example:
      LDP:     t #>> '{f1,f2,f3}'    [for compatibility across LDP 1 & 2]
      Metadb:  jsonb_extract_path_text(t, f1, f2, f3)

Report queries:
- [x] Query has complete user documentation
- [x] Purpose of report
- [x] Sample output
- [x] Query instructions

**Comment by natalyapik** [comment]
Report runs great. I have a question. There is still commented out section of the report, should it still be left commented out or need to be deleted?

**Comment by stdombek** [comment]
Thank you @natalyapik . This part remains commented out and is only used if you want to search for a time period. This was also done for the other queries for eUsage COUNTER reports https://github.com/folio-org/folio-analytics/tree/main/sql_metadb/report_queries/erm/eusage_counter_reports. :-)

**Pull request merged**
