### PR TITLE
RA/UM - Update loans_renewal_count.sql

### PR DESCRIPTION
**Pull request by eliana-flo**
I've added item HRID to the loans_renewal_count derived table, as mentioned in Issue #491. While I was at it, I also added comments.

### CODE REVIEW

**Review by nassibnassar — CHANGES_REQUESTED** [review]
The pull request Title and Description are now automatically used as the commit message (and probably will be the "release notes," instead of CHANGES.md).  So could you read over them and see if they are in the form you would want for those purposes?

**Comment by eliana-flo** [comment]
> The pull request Title and Description are now automatically used as the commit message (and probably will be the "release notes," instead of CHANGES.md). So could you read over them and see if they are in the form you would want for those purposes?

Yes, I purposely didn't update CHANGES.md knowing this. I'm satisfied with my title and description. Thank you for checking!

**Review by nassibnassar — DISMISSED** [review]

**Review by stdombek — CHANGES_REQUESTED** [review]
All queries:
- [X] PR Title and Description are accurate and thorough
- [X] PR is based on a new branch (not main)
- [X] PR scope is not overly broad
- [X] Query runs without errors
- [X] Query output is correct
- [X] Query logic is clear and well documented
- [X] Query is readable and properly indented
- [X] Table and column names are in all-lowercase
- [X] Quotation marks are used only where necessary

Derived tables:
- [ ] User documentation in comment lines, followed by blank line
- [X] File name is listed in `runlist.txt` after dependencies

- We could correct one little thing now. This was decided after the original PR for the file was created. We should place the documentation at the top, followed by a blank line, and then 'Drop...' followed by a blank line.
- The index for 'item_hrid' is missing. But according to Nassib, we don't need indexes anymore?

**Comment by eliana-flo** [comment]
> * We could correct one little thing now. This was decided after the original PR for the file was created. We should place the documentation at the top, followed by a blank line, and then 'Drop...' followed by a blank line.
> * The index for 'item_hrid' is missing. But according to @nassibnassar , we don't need indexes anymore?

I've made these changes. Thank you for the heads up!

**Review by stdombek — DISMISSED** [review]
That looks good.

**Review by VandanaShah-Cornell — APPROVED** [review]
All queries:
- [x] PR Title and Description are accurate and thorough
- [x] PR is based on a new branch (not main)
- [x] PR scope is not overly broad
- [x] Query runs without errors
- [x] Query output is correct
- [x] Query logic is clear and well documented
- [x] Query is readable and properly indented
- [x] Table and column names are in all-lowercase
- [x] Quotation marks are used only where necessary
- [x] JSON extraction is in standard form, for example:
      LDP:     t #>> '{f1,f2,f3}'    [for compatibility across LDP 1 & 2]
      Metadb:  jsonb_extract_path_text(t, f1, f2, f3)

Derived tables:
- [Not applicable, this is an LDP table ] First line is "--metadb:table" directive, followed by blank line
- [x] User documentation in comment lines, followed by blank line
- [x] File name is listed in `runlist.txt` after dependencies

**Review by nassibnassar — DISMISSED** [review]

**Pull request merged**
