### PR TITLE
added comments to public.po_lines

### PR DESCRIPTION
**Pull request by natalyapik**
```
All queries:
- [ ] Pull request is based on a new branch (not main)
- [ ] Pull request scope is not overly broad
- [ ] Release notes have been added or updated in CHANGES.md
- [ ] Query runs without errors
- [ ] Query output is correct
- [ ] Query logic is clear and well documented
- [ ] Query is readable and properly indented with spaces (not tabs)
- [ ] Table and column names are in all-lowercase
- [ ] Quotation marks are used only where necessary

Report queries:
- [ ] Query has complete user documentation
    - [ ] Purpose of report
    - [ ] Sample output
    - [ ] Query instructions

Derived tables:
- [ ] Query begins with user documentation in comment lines
- [ ] File name is listed in `runlist.txt` after dependencies
- [ ] All columns have indexes
- [ ] Table is vacuumed and analyzed
```

### CODE REVIEW

**Review by AlaoSUL — CHANGES_REQUESTED** [review]
Hey @natalyapik - 

A few lines misspelled/missing words:

Line 32: Missing the "l" in URL (comment)
Line 34: Please change current to concurrent
Line 47: Missing the "i" in receipt (column name)
Line 62: Please change accound to account (API doc is misspelled)

Since this is a public table, I am not sure if this script is suppose to contain INDEXs and  VACUUM ANALYZE on the bottom of the script. Could you please advise? Thanks! 


All queries:
- [ ] Pull request is based on a new branch (not main)
- [ ] Pull request scope is not overly broad
- [ ] Release notes have been added or updated in CHANGES.md
- [ ] Query runs without errors
- [ ] Query output is correct
- [ ] Query logic is clear and well documented
- [ ] Query is readable and properly indented with spaces (not tabs)
- [ ] Table and column names are in all-lowercase
- [ ] Quotation marks are used only where necessary

Report queries:
- [ ] Query has complete user documentation
    - [ ] Purpose of report
    - [ ] Sample output
    - [ ] Query instructions

Derived tables:
- [ ] Query begins with user documentation in comment lines
- [ ] File name is listed in `runlist.txt` after dependencies
- [ ] All columns have indexes
- [ ] Table is vacuumed and analyzed

**Comment by amzoss** [comment]
@natalyapik I am waiting to review this query until you've submitted changes based on the feedback from @AlaoSUL.

@AlaoSUL, great question about whether the `public.sql` file needs INDEXES and VACUUM ANALYZE! No, that's not necessary here. I think those need to be run when data is added to the table, and our tables in the public schema will have those commands run separately when the tables are created/updated. In this script, we're just doing that final step of adding comments, and the other stuff should already have happened.

**Review by AlaoSUL — APPROVED** [review]
All queries:
- [x] Pull request is based on a new branch (not main)
- [x] Pull request scope is not overly broad
- [x] Release notes have been added or updated in CHANGES.md
- [x] Query runs without errors
- [x] Query output is correct
- [x] Query logic is clear and well documented
- [x] Query is readable and properly indented with spaces (not tabs)
- [x] Table and column names are in all-lowercase
- [x] Quotation marks are used only where necessary


Derived tables:
- [x] Query begins with user documentation in comment lines
- [x] File name is listed in `runlist.txt` after dependencies
- [x] All columns have indexes
- [x] Table is vacuumed and analyzed

Looks good, Comments are fixed and query runs!

**Comment by amzoss** [comment]
Hi @natalyapik! Are you hoping to get this approved by tomorrow? Are there more changes coming?

**Comment by natalyapik** [comment]
We can leave it for next release.

**Review by amzoss — APPROVED** [review]
Great work on this! With the changes, the only remaining "errors" are because of the missing fields. When I add the fields that would be added by ldp_add_column.conf, everything runs without errors.

All queries:
- [x] Pull request is based on a new branch (not main)
- [x] Pull request scope is not overly broad
- [x] Release notes have been added or updated in CHANGES.md
- [x] Query runs without errors
- [x] Query output is correct
- [x] Query logic is clear and well documented
- [x] Query is readable and properly indented with spaces (not tabs)
- [x] Table and column names are in all-lowercase
- [x] Quotation marks are used only where necessary

**Pull request merged**
