### PR TITLE
Backport item_administrative_notes to LDP

### PR DESCRIPTION
**Pull request by nassibnassar**
Backport item_administrative_notes to LDP

### CODE REVIEW

**Review by LauSchl — APPROVED** [review]
works fine :)

All queries:
- [x] PR Title and Description are accurate and thorough
- [x] PR is based on a new branch (not main)
- [x] PR scope is not overly broad
- [x] Query runs without errors
- [x] Query output is correct
- [x] Query logic is clear and well documented
- [x] Query is readable and properly indented
- [x] Table and column names are in all-lowercase
- [x] Quotation marks are used only where necessary
- [x] JSON extraction is in standard form, for example:
      LDP:     t #>> '{f1,f2,f3}'    [for compatibility across LDP 1 & 2]
      Metadb:  jsonb_extract_path_text(t, f1, f2, f3)

Derived tables:
- [ ] First line is "--metadb:table" directive, followed by blank line
- [x] User documentation in comment lines, followed by blank line
- [x] File name is listed in `runlist.txt` after dependencies

**Review by VandanaShah-Cornell — COMMENTED** [review]
Question from Joanne Leary at Cornell: Why is this item_administrative_notes query pulling records where there are no administrative notes? Running this on Cornell's ldp, the results have only 24 rows of data, with about half showing [null] in the notes field. If nulls are supposed to show then why aren't the millions of other null records showing up? In the instance_administrative_notes derived table, the same thing happens - in cases where there are multiple notes, one of which is null, the record with the Null administrative note will appear in the results set. However, in cases where there is only a single administrative note, which is Null, and no other notes, the instance will still appear in the results set.

**Comment by nassibnassar** [comment]
@VandanaShah-Cornell I just saw the problem.  Some of the source data have a JSON array containing one element of null:
```
[null]
```
These can be removed with:
```
WHERE administrative_note IS NOT NULL
```

**Comment by VandanaShah-Cornell** [comment]
Hi Nassib,

I wasn’t sure how to reply to a GitHub email, so I’m copying you on your regular email. I’m also copying Joanne because I don’t know enough about the notes field.

Anyway, here is a screenshot of the results of the query (pull request #790). Joanne is puzzled as to why records with null notes are showing up in the results, and I thought that maybe all item records are included irrespective of whether they have notes or not – but in that case, running it on Cornell’s ldp, we would have millions, and not just 24 rows.

***@***.***

Thanks,
Vandana

**Comment by VandanaShah-Cornell** [comment]
I guess we are still wondering why all the other nulls didn’t show up.

**Comment by nassibnassar** [comment]
@VandanaShah-Cornell The null values you are seeing is in the JSON, and I don't know if they might be significant in some way in the FOLIO context, because they are elements in an array.  If you can determine that those nulls have no significance, we can remove them as well in the query.

**Comment by nassibnassar** [comment]
@VandanaShah-Cornell Try this query:
```
SELECT id,
       data #>> '{administrativeNotes}' AS administrative_notes
    FROM public.inventory_items
    ORDER BY length(data #>> '{administrativeNotes}') DESC;
```
It might take several minutes to run.  If you scroll down through the results, you will find administrative notes that look like this:
```
[ null ]
```
And some that look like this:
```
[]
```
The first is an array with one null element.  I'm not sure whether that information might be useful; so the array is preserved.  If the null there has no significance, we can remove the row in the derived table.

The second is an array with no elements.  Since there are no elements, there are no rows for that item in the derived table.

**Comment by VandanaShah-Cornell** [comment]
Thanks, Nassib! That’s what I understood after your last message, so I’m glad I understood it correctly. I will check with Joanne as she is the biggest user of notes.

**Comment by nassibnassar** [comment]
@VandanaShah-Cornell Also, this question can also be asked of all of the derived tables that extract JSON arrays.

**Comment by VandanaShah-Cornell** [comment]
Joanne says the rows where the notes contain just nulls are of no use and should be removed so as to not cause any confusion.

That’s a very good question about all derived tables. I can ask at the next Reporting SIG meeting.

I’m also wondering why we are spending much time on derived tables because once everyone has MetaDB, derived tables won’t be used much, right? Or will lots of institutions stay with the LDP?

**Comment by nassibnassar** [comment]
@VandanaShah-Cornell This probably needs to be confirmed with the FOLIO developers.  For example, do these JSON arrays all mean the same thing?  If we remove those null elements, they will be indistinguishable in LDP/Metadb.
```
[]
```
```
[ null ]
```
```
[ null null ]
```

**Comment by VandanaShah-Cornell** [comment]
That’s a good question for the SIG, guess we should leave it alone for now, and people can filter out the nulls in their query where they include the derived tables.
Thanks so much for clarifying all this. I’ll forward this discussion to the others.

**Review by VandanaShah-Cornell — APPROVED** [review]
- [x] PR Title and Description are accurate and thorough
- [x] PR is based on a new branch (not main)
- [x] PR scope is not overly broad
- [x] Query runs without errors
- [x] Query output is correct
- [x] Query logic is clear and well documented
- [x] Query is readable and properly indented
- [x] Table and column names are in all-lowercase
- [x] Quotation marks are used only where necessary
- [x] JSON extraction is in standard form, for example:
      LDP:     t #>> '{f1,f2,f3}'    [for compatibility across LDP 1 & 2]
      Metadb:  jsonb_extract_path_text(t, f1, f2, f3)

Derived tables:
- [x] First line is "--metadb:table" directive, followed by blank line
- [x] User documentation in comment lines, followed by blank line
- [x] File name is listed in `runlist.txt` after dependencies

**Pull request merged**
