### PR TITLE
Holdings statements index

### PR DESCRIPTION
**Pull request by natalyapik**
added new metadb holdings_statements_indexes table, also added to runlist

### CODE REVIEW

**Review by jenmawe — COMMENTED** [review]
There were no results. I think this is because there are no indexes statements in folio juniper. Is that the case?


- [x ] Query runs
- [? ] Data output makes sense
- [x ] Data types look correct
- [ x] Query logic seems correct
- [x ] Column names make sense and are spelled correctly
- [x] Query syntax and style are appropriate (e.g., correct use of double quotes, lower case for data types)

For derived tables:
- [x] query has indexes on columns
- [x ] vacuum analyze has been added to the bottom
- [ x] table appears in runlist.txt at an appropriate point

**Review by jenmawe — APPROVED** [review]

**Review by adoerrer — APPROVED** [review]
Once I added a test data set the query runs pertfectly, thank you! 

- [x] Query runs
- [x] Data output makes sense
- [x] Data types look correct
- [x] Query logic seems correct
- [x] Column names make sense and are spelled correctly
- [x] Query syntax and style are appropriate (e.g., correct use of double quotes, lower case for data types)

For derived tables:
- [x] query has indexes on columns
- [x] vacuum analyze has been added to the bottom
- [x] table appears in runlist.txt at an appropriate point

**Review by nassibnassar — CHANGES_REQUESTED** [review]
The file name does not match the file name added to runlist or the query name.  Which name would you prefer to use?

**Comment by nassibnassar** [comment]
The file name problem turned into a bit of a mess.  I will fix it in the merge.

**Pull request merged**
