### PR TITLE
ERM/ACQ - Update for derived table "finance_invoice_transactions.sql"

### LINKED ISSUE #791: ERM/ACQ - Add expense class to derived table "finance_invoice_transactions.sql"
In FOLIO it is possible to select a fund several times within the fund distribution in an invoice line if the expense class is different. In order for the derived table "[finance_invoice_transactions.sql](https://github.com/folio-org/folio-analytics/blob/92b62956e3149ef4c1f2e5f2857ffce6eec7ff76/sql_metadb/derived_tables/finance_invoice_transactions.sql)" to work properly, this functionality must be added to the SQL statement.

### PR DESCRIPTION
**Pull request by stdombek**
Closes #791 
Added `expense class informations` and the `external account number extension` to the derived table "finance_invoice_transactions.sql".

With this derived table we have the opportunity to view all invoice lines regardless of the workflow status. The invoice lines are linked to the transactions if one exists. The expense classes have been newly added. You can now see what expense class the transactions and invoice lines are.

### CODE REVIEW

**Comment by stdombek** [comment]
I added the necessary directive from Metadb to ensure the required table "expense_class__t".

**Comment by VandanaShah-Cornell** [comment]
Hi, 
One comment, if you can make this quick change before it gets merged: In your comment statement "COMMENT ON COLUMN finance_invoice_transactions.invoice_line_distribution_type IS 'Percentage or amount type of the value property';" I was confused by the word 'property' at the end. Maybe that should be deleted, or else it should be "Property of the value (percentage or amount)" or it can be "Type of value (percentage or amount)".
I approved the pull request but for some reason the checklist shows that 'Query runs without errors' does not have a green checkmark next to it. So just to clarify, it DOES run without any errors.

**Comment by stdombek** [comment]
Thank you @VandanaShah-Cornell . I changed the comment for the column.

**Review by trapido — APPROVED** [review]
Looks great!

All queries:
- [x] PR Title and Description are accurate and thorough
- [x] PR is based on a new branch (not main)
- [x] PR scope is not overly broad
- [x] Query runs without errors
- [x] Query output is correct
- [x] Query logic is clear and well documented
- [x] Query is readable and properly indented
- [x] Table and column names are in all-lowercase
- [x] Quotation marks are used only where necessary
- [x] JSON extraction is in standard form, for example:
      LDP:     t #>> '{f1,f2,f3}'    [for compatibility across LDP 1 & 2]
      Metadb:  jsonb_extract_path_text(t, f1, f2, f3)

Derived tables:
- [x] First line is "--metadb:table" directive, followed by blank line
- [x] User documentation in comment lines, followed by blank line
- [x] File name is listed in `runlist.txt` after dependencies

**Pull request merged**
