### PR TITLE
adding a new derived table to unpack service points

### LINKED ISSUE #396: RA/UM create derived table matching service points to libraries

### PR DESCRIPTION
**Pull request by amzoss**
will close #396

### CODE REVIEW

**Comment by lib-eric** [comment]
Looks good and able to run in our local instance. I see adds updated on dep and runlist, awesome.

I am noticing a lot of **service_point_discovery_display_name** and **service_point_name** that are "Unassigned" for locations that do not circulate. If that is the expected behavior I think this is good! Nice job!!

**Comment by amzoss** [comment]
Thanks, @lib-eric! Glad to hear it's running on your local instance! I'm not completely surprised that the service point name fields aren't completely filled in, as I expect that varies a fair amount by institution.

**Comment by amzoss** [comment]
@nassibnassar do you need @lib-eric to officially approve the review?

**Review by lib-eric — APPROVED** [review]
Looks good!

**Review by nassibnassar — APPROVED** [review]

**Pull request merged**
