### PR TITLE
Create metadb derived table item_tags

### PR DESCRIPTION
**Pull request by lib-eric**
Create a metadb derived table for items with tags. Table contains a new row for every tag associated with an item record and contains the name of the tag and ordinality the tag appears in.

### CODE REVIEW

**Review by stdombek — APPROVED** [review]
- [X] Query runs
- [X] Data output makes sense
- [X] Data types look correct
- [X] Query logic seems correct
- [X] Column names make sense and are spelled correctly
- [X] Query syntax and style are appropriate (e.g., correct use of double quotes, lower case for data types)

For derived tables:
- [X] query has indexes on columns
- [X] vacuum analyze has been added to the bottom
- [X] table appears in runlist.txt at an appropriate point

**Review by jenmawe — APPROVED** [review]
- [x] Query runs
- [x] Data output makes sense
- [x] Data types look correct
- [x] Query logic seems correct
- [x] Column names make sense and are spelled correctly
- [x] Query syntax and style are appropriate (e.g., correct use of double quotes, lower case for data types)

For derived tables:
- [x] query has indexes on columns
- [x] vacuum analyze has been added to the bottom
- [x] table appears in runlist.txt at an appropriate point

**Review by nassibnassar — CHANGES_REQUESTED** [review]
If possible could we have a PR description: https://github.com/folio-org/folio-analytics/blob/main/CONTRIBUTING.md#pull-request-description

**Comment by jenmawe** [comment]
@lib-eric I noticed that you didn't include the item hrid. Did you want to do that? Our other derived tables include both id and hrid.

**Comment by lib-eric** [comment]
> @lib-eric I noticed that you didn't include the item hrid. Did you want to do that? Our other derived tables include both id and hrid.

Good point @jenmawe , added!

**Review by stdombek — APPROVED** [review]

**Comment by adoerrer** [comment]
> If possible could we have a PR description: https://github.com/folio-org/folio-analytics/blob/main/CONTRIBUTING.md#pull-request-description

I think this is solved now and the PR is ready to be merged, thanks.

**Pull request merged**
