### PR TITLE
Fixes #344

### LINKED ISSUE #344: Add Holdings and Items discovery_suppress to the Title Count and Item Count queries
Add Holdings discovery_suppress to the Title Count query.
Add Holdings discovery_suppress and Items discovery_suppress to the Item Count query.
Should be added as harcoded filters, same as Instance discovery_suppress.

### PR DESCRIPTION
**Pull request by adoerrer**
Added Holdings and Items discovery_suppress to the Title Count and Item Count queries and updated query documentation

### CODE REVIEW

**Review by LM-15 — COMMENTED** [review]
Hi Axel-
I would remove any text about "at least one unsuppressed holdings record" (because they don't have to worry about this - sorry I added earlier) and "suppress values are true" (because that doesn't seem to be what is used?) .  So each would be:
Excludes suppressed instance and holdings records (for title counts)
OR
Excludes suppressed instance, holdings and item records (for item counts)

as appropriate.

I'm guessing the "inst.discovery_suppress ISNULL" should not be needed in real life, but it doesn't hurt.

**Comment by LM-15** [comment]
Not sure I'm using this correctly Nassib.  Linda

**Comment by adoerrer** [comment]
> Hi Axel-
> I would remove any text about "at least one unsuppressed holdings record" (because they don't have to worry about this - sorry I added earlier) and "suppress values are true" (because that doesn't seem to be what is used?) . So each would be:
> Excludes suppressed instance and holdings records (for title counts)
> OR
> Excludes suppressed instance, holdings and item records (for item counts)
> 
> as appropriate.
> 
> I'm guessing the "inst.discovery_suppress ISNULL" should not be needed in real life, but it doesn't hurt.

Thank you Linda! I've added your suggestions to the PR now. And `inst.discovery_suppress ISNULL` is there in case this field has not been set.

**Review by nassibnassar — CHANGES_REQUESTED** [review]
Could we use the more standard `IS NULL` rather than `ISNULL`?

**Comment by adoerrer** [comment]
> Could we use the more standard `IS NULL` rather than `ISNULL`?
Thank you, have now made that changes.

**Review by LM-15 — APPROVED** [review]

**Review by nassibnassar — APPROVED** [review]

**Pull request merged**
