### PR TITLE
ACQ/ERM - LDP1 version of finance_funds derived table

### LINKED ISSUE #728: Create LDP1 version of new finance_funds derived table
Create LDP1 version of finance_funds

### PR DESCRIPTION
**Pull request by stdombek**
Closes #728 

This is a version for LDP1 of the already existing version for [Metadb](https://github.com/folio-org/folio-analytics/blob/main/sql_metadb/derived_tables/finance_funds.sql).

**Note: The community discussed in the meeting that this PR can be uploaded without testing. This does not conform to the rules of CONTRIBUTING.md. It was determined that the reviewers would test the PR themselves using real data.** 

```
All queries:
- [ ] Pull request is based on a new branch (not main)
- [ ] Pull request scope is not overly broad
- [ ] Release notes have been added or updated in CHANGES.md
- [ ] Query runs without errors
- [ ] Query output is correct
- [ ] Query logic is clear and well documented
- [ ] Query is readable and properly indented with spaces (not tabs)
- [ ] Table and column names are in all-lowercase
- [ ] Quotation marks are used only where necessary

Report queries:
- [ ] Query has complete user documentation
    - [ ] Purpose of report
    - [ ] Sample output
    - [ ] Query instructions

Derived tables:
- [ ] Query begins with user documentation in comment lines
- [ ] File name is listed in `runlist.txt` after dependencies
- [ ] All columns have indexes
- [ ] Table is vacuumed and analyzed
```

### CODE REVIEW

**Review by natalyapik — CHANGES_REQUESTED** [review]
All queries:
- [x ] Pull request is based on a new branch (not main)
- [x ] Pull request scope is not overly broad
- [x ] Release notes have been added or updated in CHANGES.md
- [x ] Query runs without errors
- [x ] Query output is correct
- [x ] Query logic is clear and well documented
- [x ] Query is readable and properly indented with spaces (not tabs)
- [ x] Table and column names are in all-lowercase
- [x ] Quotation marks are used only where necessary

Report queries:
- [] Query has complete user documentation
    - [ ] Purpose of report
    - [ ] Sample output
    - [ ] Query instructions

Derived tables:
- [x ] Query begins with user documentation in comment lines
- [ x] File name is listed in `runlist.txt` after dependencies
- [x ] All columns have indexes
- [x ] Table is vacuumed and analyzed
I ran it in our LDP environment and it looks good. The only minor thing is we put VACUUM ANALYZE before comments, it is after right now.

**Comment by stdombek** [comment]
I always set the line `VACUUM ANALYZE` at the end in this repository. There is no exact rule as to where that should be or I can't find it. However, it makes sense to do it at the end.

**Review by natalyapik — APPROVED** [review]
Thank you Stefan!

**Review by sbeltaine — CHANGES_REQUESTED** [review]
All queries:
- [ x] Pull request is based on a new branch (not main)
- [x ] Pull request scope is not overly broad
- [ x] Release notes have been added or updated in CHANGES.md
- [x ] Query runs without errors
- [x ] Query output is correct
- [ x] Query logic is clear and well documented
- [ x] Query is readable and properly indented with spaces (not tabs)
- [x ] Table and column names are in all-lowercase
- [x ] Quotation marks are used only where necessary

Report queries:
- [ ] Query has complete user documentation
    - [ ] Purpose of report
    - [ ] Sample output
    - [ ] Query instructions

Derived tables:
- [ x] Query begins with user documentation in comment lines
- [ x] File name is listed in `runlist.txt` after dependencies
- [ x] All columns have indexes
- [ x] Table is vacuumed and analyzed
I tested this derived table in Cornell's LDP1 instance and it ran fine. My only suggestion is a different name for this derived table. We have a public.finance_funds table. It is confusing to have public and derived tables with the same name. Perhaps "fund_ext" or "finance_fund_ext" would be better?

**Comment by stdombek** [comment]
The community decided that the table should be called "finance_fund_ext". I create the change this week.

**Comment by stdombek** [comment]
I changed the name of the derived table because there was a naming conflict with the table in the schema public. In the meeting, the community agreed on the name `finance_funds_ext`.

**Review by natalyapik — APPROVED** [review]
looks good

**Review by sbeltaine — APPROVED** [review]
Reviewed second time after table name change. Approved.

**Pull request merged**
