### PR TITLE
updated po instances and created prod ids

### PR DESCRIPTION
**Pull request by natalyapik**

### CODE REVIEW

**Comment by jenmawe** [comment]
@nassibnassar Would you mind looking at the conflict? I tried to do this with Natalya but we didn't get the option to resolve the conflict.

**Comment by jenmawe** [comment]
closes #346

**Comment by nassibnassar** [comment]
Do you have a sense of what was changed in po_instance.sql?  Otherwise it will require a word by word comparison.

**Comment by natalyapik** [comment]
yes, we added wf_status, po_line_number, and changed created_by from json to user_users table.
________________________________

**Comment by nassibnassar** [comment]
Thank you.  I also see pol_instance_hrid added.

I'll fix the typo in
```CREATE INDEX ON folio_reporting.po_instance (pol_intance_id);```

Has this been tested?

**Comment by nassibnassar** [comment]
Also added po_lines.selector.

**Comment by jenmawe** [comment]
@nassibnassar I can test in sandbox and Natalya also tested it at Cornell and Christie at Chicago.

**Comment by nassibnassar** [comment]
@natalyapik @jenmawe I'm unsure about this:
```
json_extract_path_text(po_purchase_orders.data, 'metadata', 'createdByUserId') AS created_by,
```
vs.
```
user_users.username AS created_by,
```

Which one would you like to keep?  Or both?

**Pull request merged**
