### PR TITLE
ERM - New directory structure

### LINKED ISSUE #664: ERM - New directory structure for sql_metadb/report_queries/erm/
In the dev meeting it was decided to improve the directory structure of sql_metadb/report_queries/erm. All report queries in this subdirectory "erm" will be placed on one level. Each query gets a subdirectory containing the SQL file and the README.md.

### PR DESCRIPTION
**Pull request by stdombek**
Closes #664 

1. Moved files for new directory structure as discussed in meeting.
2. Created new README files that were missing.
    * ERM Agreements cancellation dates
    * ERM Agreements package content item list

### CODE REVIEW

**Comment by stdombek** [comment]
I'm not entirely sure what that means. In the new version, each query has its own subdirectory in /erm. Has the new version been viewed? You can also see the new structure in my Fork in branch Iss664 [Link ](https://github.com/stdombek/folio-analytics/tree/Iss664/sql_metadb/report_queries/erm).

**Comment by AlaoSUL** [comment]
Hey @stdombek , my mistake, I must have viewed the incorrect version. 

Upon viewing your hyperlink, all files/queries have their own subdirectories in /erm and respective README as discussed in our meetings.

1. Moved files for new directory structure as discussed in meeting. - Completed 
2. Created new README files that were missing. - Completed 
- ERM Agreements cancellation dates
- ERM Agreements package content item list

**Review by AlaoSUL — APPROVED** [review]
All files/queries have their own subdirectories in /erm and respective README as discussed in our meetings. @stdombek 

Moved files for new directory structure as discussed in meeting. - Completed
Created new README files that were missing. - Completed
ERM Agreements cancellation dates
ERM Agreements package content item list

**Review by amzoss — CHANGES_REQUESTED** [review]
Overall this looks great, except that one of the filenames seems to have gotten messed up. 
In [agreement_fund_distribution_by_fiscal_years](https://github.com/stdombek/folio-analytics/tree/Iss664/sql_metadb/report_queries/erm/agreement_fund_distribution_by_fiscal_years), the file is named `erm_agreemeerm_agreement_fund_distribution_by_fiscal_years.sql`. I think it should just be `erm_agreement_fund_distribution_by_fiscal_years.sql`.

**Comment by stdombek** [comment]
Thank you @amzoss and @AlaoSUL for the review. The error with the file name probably crept in when renaming the path via the GitHub webUI. The file name has been corrected. :-)

**Review by amzoss — APPROVED** [review]
Thanks, looks good!

**Review by AlaoSUL — APPROVED** [review]
hey @stdombek, looks good now!

**Pull request merged**
