### PR TITLE
Fix erm_agreement_cancellation_dates

### LINKED ISSUE #619: ERM - Fix erm_agreement_cancellation_dates.sql
[Query](https://github.com/folio-org/folio-analytics/blob/main/sql_metadb/report_queries/erm/resource_lists/erm_agreement_cancellation_dates.sql) stops with error: "operator does not exist: text = uuid"

### PR DESCRIPTION
**Pull request by stdombek**
Closes #619 

- The query has been adapted to the new data schema.
- Optimizations: Deleted an unused table and removed unnecessary aliases.

### CODE REVIEW

**Comment by nassibnassar** [comment]
- [ ] Pull request has a complete description
- [ ] Query runs without errors
- [ ] Query output is correct
- [ ] Query logic is clear and well documented
- [ ] Query is readable and properly indented
- [ ] Table and column names are in all-lowercase
- [ ] Quotation marks are used only where necessary
- [ ] Query has complete user documentation
  Purpose of report
  Sample output
  Query instructions

**Review by adoerrer — CHANGES_REQUESTED** [review]
> * [x]  Pull request has a complete description
> 
>     * [x]  Query runs without errors
> 
>     * [x]  Query output is correct
> 
>     * [x]  Query logic is clear and well documented
> 
>     * [x]  Query is readable and properly indented
> 
>     * [x]  Table and column names are in all-lowercase
> 
>     * [x]  Quotation marks are used only where necessary
> 
>     * [ ]  Query has complete user documentation
>       Purpose of report
>       Sample output
>       Query instructions

Thank you, Stefan! The fixes look good, but there's some documentation on the sample out put and the query instructions missing. You could use one of the older documentation as a template. eg. https://github.com/folio-org/folio-analytics/blob/main/sql/report_queries/erm/erm_order_status.md

**Comment by stdombek** [comment]
The documentation for the report queries "[resource_lists](https://github.com/folio-org/folio-analytics/tree/main/sql_metadb/report_queries/erm/resource_lists)" for metadb has been kept very minimalist until now. We're very welcome to use the concept of documentation as in the rest of the repository now.

**Comment by stdombek** [comment]
Directory structure still needs to be discussed in wg erm. Issue moved to release 1.5.

**Comment by stdombek** [comment]
PR is closed. The fix will be submitted with a new PR as soon as issue #664 (New directory structure for sql_metadb/report_queries/erm/) is merged.

**Pull request closed without merging**
