### PR TITLE
Add derived table to extract fund distribution from po_lines

### PR DESCRIPTION
**Pull request by nassibnassar**
Fund distribution is a JSON array in "public.po_lines".  This query extracts the arrays into a table.

### CODE REVIEW

**Comment by stdombek** [comment]
What ist the different to PR #745 ?

**Comment by nassibnassar** [comment]
> What is the difference to PR #745 ?

Probably no difference.  Someone asked me today how to extract the array, and I had forgotten about #745 .  I will look at both PRs and merge them together.

**Comment by stdombek** [comment]
That sounds good. Your request is based on the new criteria. So I would suggest taking this one and just adding the comments from the other. :-)

**Comment by nassibnassar** [comment]
Closing, changes moved to PR #788

**Pull request closed without merging**
