### PR TITLE
ACQ - updated metadb table name to match LDP table name - po_lines_vendor_reference_numbers

### LINKED ISSUE #757: ACQ - correct name for po_line_vendor_reference_number.sql for Metadb
Update derived table name from "po_line_vendor_reference_number.sql" to "po_lines_vendor_reference_numbers.sql" for Metadb.

### PR DESCRIPTION
**Pull request by sbeltaine**
Closes #757

Updated filename for "po_line_vendor_reference_number" to "po_lines_vendor_reference_numbers" to match equivalent LDP table name. 
Also updated entry for "po_line_vendor_reference_number" to "po_lines_vendor_reference_numbers" in runlist.txt file for metadb. 
Also updated  "--metadb:table po_line_vendor_reference_number" to "--metadb:table po_lines_vendor_reference_numbers" at top of query.

Documented this update on the 1.7 (Poppy) release notes at https://github.com/folio-org/folio-analytics/wiki/Changes-by-Release

### CODE REVIEW

**Review by stdombek — APPROVED** [review]
No checklist required

**Review by trapido — APPROVED** [review]
Looks good!

**Review by nassibnassar — CHANGES_REQUESTED** [review]
This looks to me like the file name and --metadb:table directive were changed, but now they no longer match the table name.

**Review by stdombek — CHANGES_REQUESTED** [review]
I can confirm that. I didn't notice that in the first review.

**Comment by nassibnassar** [comment]
I think I understand the intended purpose of this PR and can make the changes.

What about `po_line_fund_distribution_transactions.sql`?

**Comment by nassibnassar** [comment]
@sbeltaine When I make this change, shall I also do the same for  `po_line_fund_distribution_transactions`?

**Comment by sbeltaine** [comment]
I updated all the references to the po_lines_vendor_reference_numbers table per your comment, @nassibnassar

**Comment by sbeltaine** [comment]
Yes, @nassibnassar - It would be great if you would kindly make the same changes to the po_line_fund_distribution_transactions table.

**Comment by nassibnassar** [comment]
Changes made in commit bae22f9122e8d11e5744f1f62be8058d9687dbd9

**Pull request closed without merging**
