### PR TITLE
Updated MM Instance ext

### PR DESCRIPTION
**Pull request by jenmawe**
This closes issue #703. Comments have also been added.
```
All queries:
- [ ] Pull request is based on a new branch (not main)
- [ ] Pull request scope is not overly broad
- [ ] Release notes have been added or updated in CHANGES.md
- [ ] Query runs without errors
- [ ] Query output is correct
- [ ] Query logic is clear and well documented
- [ ] Query is readable and properly indented with spaces (not tabs)
- [ ] Table and column names are in all-lowercase
- [ ] Quotation marks are used only where necessary

Report queries:
- [ ] Query has complete user documentation
    - [ ] Purpose of report
    - [ ] Sample output
    - [ ] Query instructions

Derived tables:
- [ ] Query begins with user documentation in comment lines
- [ ] File name is listed in `runlist.txt` after dependencies
- [ ] All columns have indexes
- [ ] Table is vacuumed and analyzed
```

### CODE REVIEW

**Review by natalyapik — COMMENTED** [review]
All queries:
- [v ] Pull request is based on a new branch (not main)
- [v ] Pull request scope is not overly broad
- [v ] Release notes have been added or updated in CHANGES.md
- [v ] Query runs without errors
- [ ] Query output is correct
- [v ] Query logic is clear and well documented
- [v ] Query is readable and properly indented with spaces (not tabs)
- [v ] Table and column names are in all-lowercase
- [ v] Quotation marks are used only where necessary

Report queries:
- [ ] Query has complete user documentation
    - [ ] Purpose of report
    - [ ] Sample output
    - [ ] Query instructions

Derived tables:
- [v ] Query begins with user documentation in comment lines
- [v ] File name is listed in `runlist.txt` after dependencies
- [v ] All columns have indexes
- [v ] Table is vacuumed and analyzed

If possible to add some fields that are missing in LDP table but are present in metadb. Fields missing are: is_bound_with, instance_type_id, instance_type_id_name, match_key, created_date. Indexes and comments would need to be added as well. Comments are correct otherwise.

**Review by LauSchl — CHANGES_REQUESTED** [review]
All queries:
- [x] Pull request is based on a new branch (not main)
- [x] Pull request scope is not overly broad
- [x] Release notes have been added or updated in CHANGES.md
- [ ] Query runs without errors
- [x] Query output is correct
- [x] Query logic is clear and well documented
- [x] Query is readable and properly indented with spaces (not tabs)
- [x] Table and column names are in all-lowercase
- [x] Quotation marks are used only where necessary

Derived tables:
- [x] Query begins with user documentation in comment lines
- [x] File name is listed in `runlist.txt` after dependencies
- [x] All columns have indexes
- [x] Table is vacuumed and analyzed

Comment: Error in line 92 the column name is status_updated_date instead of status_update_date

**Comment by amzoss** [comment]
@jenmawe are you trying to get this approved for Orchid? if not, maybe this PR should be closed and resubmitted after the release?

**Comment by jenmawe** [comment]
> @jenmawe are you trying to get this approved for Orchid? if not, maybe this PR should be closed and resubmitted after the release?

Originally, the pull request was just to remove the duplicate field for the record source and add comments.  For those fields that Natalya says are missing (Fields missing are: is_bound_with, instance_type_id, instance_type_id_name, match_key, created_date), created date is already there. Nothing has is_bound_with right now so I couldn't find it. ALso, instance_type_id and id name are fields I couldn't find in the API documentation. 

Would it make sense to push this through just for removing the duplicate field and comments and then create a new PR to enhance the instance_ext with new fields?

**Pull request closed without merging**
