### PR TITLE
RM/ERM - New derived table finance_funds

### LINKED ISSUE #702: RM/ERM - Create derived table for finance data
There should be a derived table for reporting that contains all financial data. The financial data must be linked in a very specific way to get a correct output. The derived table should make it easier to use the financial data.

### PR DESCRIPTION
**Pull request by stdombek**
Closes #702 

This is a new derived table for metadb to show financial data.

```
All queries:
- [ ] Pull request is based on a new branch (not main)
- [ ] Pull request scope is not overly broad
- [ ] Release notes have been added or updated in CHANGES.md
- [ ] Query runs without errors
- [ ] Query output is correct
- [ ] Query logic is clear and well documented
- [ ] Query is readable and properly indented with spaces (not tabs)
- [ ] Table and column names are in all-lowercase
- [ ] Quotation marks are used only where necessary

Report queries:
- [ ] Query has complete user documentation
    - [ ] Purpose of report
    - [ ] Sample output
    - [ ] Query instructions

Derived tables:
- [ ] Query begins with user documentation in comment lines
- [ ] File name is listed in `runlist.txt` after dependencies
- [ ] All columns have indexes
- [ ] Table is vacuumed and analyzed
```

### CODE REVIEW

**Review by eliana-flo — APPROVED** [review]
Everything checks out and the query is very readable/organized. The only thing I really noticed is that some of your comments are a little inconsistent (you describe the fund code as "unique" and the fund status as "current," but you don't use those qualifiers for the other codes/statuses which has the potential to cause confusion). Other than that, looks perfect. 

All queries:
- [x] Pull request is based on a new branch (not main)
- [x] Pull request scope is not overly broad
- [x] Release notes have been added or updated in CHANGES.md
- [x] Query runs without errors
- [x] Query output is correct
- [x] Query logic is clear and well documented
- [x] Query is readable and properly indented with spaces (not tabs)
- [x] Table and column names are in all-lowercase
- [x] Quotation marks are used only where necessary

Derived tables:
- [x] Query begins with user documentation in comment lines
- [x] File name is listed in `runlist.txt` after dependencies
- [x] All columns have indexes
- [x] Table is vacuumed and analyzed

**Comment by stdombek** [comment]
Thank you @eliana-flo . The descriptions in the comments are 1:1 from the FOLIO API documentation. It is confusing and this is the reason for this table. The fund id is unique, but can be used over several fiscal years. The status indicates the current one. It is not the case with the others attributes, just with funds. The joining of the tables is in the exact order in which the funds are assigned to the correct fiscal year. This is the only way. Later you can connect this table with the transactions table. To do this, you have to connect the transactions with this table via the attributes fiscal year id and fund id at the same time via "and" in the join part.

**Comment by nassibnassar** [comment]
If possible, please add
```
--metadb:table finance_funds
```
as the very first line of the file, followed by a blank line.

This will help Metadb to report on progress of loading the derived tables.  See for example:  https://github.com/folio-org/folio-analytics/blob/main/sql_metadb/derived_tables/holdings_notes.sql

**Comment by stdombek** [comment]
@nassibnassar I added the line at the top.

**Review by arthur-aguilera — APPROVED** [review]
All queries:
- [x] Pull request is based on a new branch (not main)
- [x] Pull request scope is not overly broad
- [x] Release notes have been added or updated in CHANGES.md
- [X] Query runs without errors
- [X] Query output is correct
- [X] Query logic is clear and well documented
- [X] Query is readable and properly indented with spaces (not tabs)
- [X] Table and column names are in all-lowercase
- [X] Quotation marks are used only where necessary

Report queries:
- [ ] Query has complete user documentation
    - [ ] Purpose of report
    - [ ] Sample output
    - [ ] Query instructions

Derived tables:
- [x] Query begins with user documentation in comment lines
- [x] File name is listed in `runlist.txt` after dependencies
- [x] All columns have indexes
- [x] Table is vacuumed and analyzed

**Comment by nassibnassar** [comment]
merged as 78fc11e

**Pull request closed without merging**
